os:
  - osx
  - linux

osx_image: xcode8

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable fluxbox
      - xvfb

language: node_js

node_js:
  - 6
  - 7
  - 8

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &

script:
 - npm run coverage
 - npm run client

after_script:
 - npm install coveralls@2.10.0
 - cat ./coverage/lcov.info | coveralls
